#!/usr/bin/env bash
# shellcheck disable=SC2086
# Configure the subdomain.

if [ $# -eq 1 ]
then
    domain="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
    domain="$2.$1"
fi
dig $domain | awk '/ANSWER SECTION:/{getline; split($1,i,"."); printf "The subdomain %s is a %s record and points to %s\n", i[1], $4, $5}'
