#!/usr/bin/env bash
# Redirect a webpage with nginx.
apt-get -y update
apt-get -y install nginx
echo 'Hello World' > /var/www/html/index.html
sed -i "/server_name _;/a rewrite ^/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
ufw allow 'Nginx HTTP'
sudo service nginx restart
