#!/usr/bin/env bash
# Redirect a webpage.
apt-get update
apt-get -y install nginx
echo 'Hello World' > /var/www/html/index.html
# sed -i s/"string_to_replace"/"${new_string}"/g $file
new_string = 'server_name _;\nlocation \/redirect_me \n\trewrite ^/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;'
sed -i s/'server_name _;'\'${new_string}\'/g /etc/nginx/sites-available/default 
# 's/server_name _;\nlocation\n\trewrite ^/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
ufw allow 'nginx HTTP'
service nginx restart

#server
#    location /redirect_me {
#       return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;    rewrite ^/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;
#    } 