#!/usr/bin/env bash
# Display 10 times Best school but with Hi in the 9TH index
i=1
while [ $i -le 10 ]
do 
    if [ "$i" == 10 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    i=$(( i + 1 ))
done
