#!/usr/bin/env bash
# Display bad luck in the 4TH index and good luck in the 8TH index.
i=0
while [ $i -lt 10 ]
do
    if [ "$i" == 3 ]
    then
        echo "bad luck"
    elif [ "$i" == 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$(( i + 1 ))
done
