#!/usr/bin/env bash
# Check if the file exist.
FILE="school"
if [ -e "$FILE" ]; then
    echo "school file exists"
    if [ -f "$FILE" ]; then
        echo "school is a regular file"
    elif [ -s "$FILE" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
