#!/usr/bin/env bash
# Run nginx as nginx with less lines.
pkill apache2
chmod 006 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
